#!/usr/bin/env bash
# OpenClaw Production Setup Script
# Khalil Krimech — AI Portfolio & Agentic System
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
#
# What this script does:
#   1. Validates prerequisites (Docker, Docker Compose)
#   2. Creates config and workspace directories
#   3. Generates a gateway token (if not already set)
#   4. Writes the .env file
#   5. Builds the Docker image
#   6. Runs the onboarding wizard (interactive)
#   7. Starts the gateway
#   8. Prints next steps (Telegram setup, device pairing)

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"

# ─── Colors ───────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

# ─── Prerequisites ────────────────────────────────────────────────────
info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || fail "Docker is not installed."
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is not available."

ok "Docker and Docker Compose are available."

# ─── Configuration ────────────────────────────────────────────────────
OPENCLAW_CONFIG_DIR="${OPENCLAW_CONFIG_DIR:-$HOME/.openclaw}"
OPENCLAW_WORKSPACE_DIR="${OPENCLAW_WORKSPACE_DIR:-$HOME/.openclaw/workspace}"
OPENCLAW_IMAGE="${OPENCLAW_IMAGE:-openclaw:local}"
OPENCLAW_GATEWAY_PORT="${OPENCLAW_GATEWAY_PORT:-18789}"
OPENCLAW_BRIDGE_PORT="${OPENCLAW_BRIDGE_PORT:-18790}"
OPENCLAW_GATEWAY_BIND="${OPENCLAW_GATEWAY_BIND:-lan}"

mkdir -p "$OPENCLAW_CONFIG_DIR" "$OPENCLAW_WORKSPACE_DIR"
ok "Config directory: $OPENCLAW_CONFIG_DIR"
ok "Workspace directory: $OPENCLAW_WORKSPACE_DIR"

# ─── Gateway Token ────────────────────────────────────────────────────
if [[ -z "${OPENCLAW_GATEWAY_TOKEN:-}" ]]; then
  if [[ -f "$ENV_FILE" ]] && grep -q '^OPENCLAW_GATEWAY_TOKEN=' "$ENV_FILE"; then
    # Reuse existing token from .env
    OPENCLAW_GATEWAY_TOKEN="$(grep '^OPENCLAW_GATEWAY_TOKEN=' "$ENV_FILE" | cut -d= -f2-)"
    if [[ -n "$OPENCLAW_GATEWAY_TOKEN" ]]; then
      ok "Reusing existing gateway token from .env"
    fi
  fi
fi

if [[ -z "${OPENCLAW_GATEWAY_TOKEN:-}" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    OPENCLAW_GATEWAY_TOKEN="$(openssl rand -hex 32)"
  else
    OPENCLAW_GATEWAY_TOKEN="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
  fi
  ok "Generated new gateway token."
fi

# ─── Write .env ───────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
OPENCLAW_CONFIG_DIR=$OPENCLAW_CONFIG_DIR
OPENCLAW_WORKSPACE_DIR=$OPENCLAW_WORKSPACE_DIR
OPENCLAW_IMAGE=$OPENCLAW_IMAGE
OPENCLAW_GATEWAY_PORT=$OPENCLAW_GATEWAY_PORT
OPENCLAW_BRIDGE_PORT=$OPENCLAW_BRIDGE_PORT
OPENCLAW_GATEWAY_BIND=$OPENCLAW_GATEWAY_BIND
OPENCLAW_GATEWAY_TOKEN=$OPENCLAW_GATEWAY_TOKEN

# Suppress Docker Compose warnings for image-referenced variables.
CLAUDE_AI_SESSION_KEY=
CLAUDE_WEB_SESSION_KEY=
CLAUDE_WEB_COOKIE=
EOF

ok "Wrote .env file."

# ─── Build Image ──────────────────────────────────────────────────────
info "Building Docker image: $OPENCLAW_IMAGE"

if [[ -f "$ROOT_DIR/Dockerfile" ]]; then
  docker build \
    --build-arg "OPENCLAW_DOCKER_APT_PACKAGES=${OPENCLAW_DOCKER_APT_PACKAGES:-}" \
    -t "$OPENCLAW_IMAGE" \
    -f "$ROOT_DIR/Dockerfile" \
    "$ROOT_DIR"
  ok "Image built successfully."
else
  warn "No Dockerfile found in $ROOT_DIR."
  warn "Assuming image '$OPENCLAW_IMAGE' already exists or will be pulled."
fi

# ─── Onboarding ───────────────────────────────────────────────────────
info "Starting onboarding wizard..."
echo ""
echo "  When prompted:"
echo "    Gateway bind:    lan"
echo "    Gateway auth:    token"
echo "    Gateway token:   $OPENCLAW_GATEWAY_TOKEN"
echo "    Tailscale:       Off"
echo "    Install daemon:  No"
echo ""

docker compose --profile cli run --rm openclaw-cli onboard --no-install-daemon

# ─── Sync Token to Config ───────────────────────────────────────────
# After onboarding, the config file may have a different or empty token.
# Force-sync the .env token so all consumers agree.
OPENCLAW_JSON="$OPENCLAW_CONFIG_DIR/openclaw.json"
if [[ -f "$OPENCLAW_JSON" ]]; then
  python3 -c "
import json
with open('$OPENCLAW_JSON','r') as f: cfg = json.load(f)
cfg.setdefault('gateway',{}).setdefault('auth',{})['token'] = '$OPENCLAW_GATEWAY_TOKEN'
with open('$OPENCLAW_JSON','w') as f: json.dump(cfg, f, indent=2)
" && ok "Token synced to openclaw.json" || warn "Could not sync token (non-fatal, Docker env var takes precedence)"
  chmod 600 "$OPENCLAW_JSON"
  ok "Config file permissions set to 600."
fi

# ─── Add Telegram Channel ────────────────────────────────────────────
echo ""
read -rp "Do you want to add a Telegram bot now? (y/N): " ADD_TELEGRAM
if [[ "$ADD_TELEGRAM" =~ ^[Yy]$ ]]; then
  read -rp "Enter your Telegram bot token: " TELEGRAM_TOKEN
  docker compose --profile cli run --rm openclaw-cli channels add \
    --channel telegram --token "$TELEGRAM_TOKEN"
  ok "Telegram channel added."
fi

# ─── Start Gateway ───────────────────────────────────────────────────
info "Starting gateway..."
docker compose up -d openclaw-gateway
ok "Gateway is running."

# ─── Summary ──────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  OpenClaw is running!"
echo ""
echo "  Gateway token:   $OPENCLAW_GATEWAY_TOKEN"
echo "  Dashboard:       http://127.0.0.1:$OPENCLAW_GATEWAY_PORT/"
echo ""
echo "  Access via SSH tunnel:"
echo "    ssh -L $OPENCLAW_GATEWAY_PORT:127.0.0.1:$OPENCLAW_GATEWAY_PORT user@your-vps"
echo ""
echo "  Then open http://localhost:$OPENCLAW_GATEWAY_PORT/ in your browser."
echo "  Paste the gateway token in Settings to authenticate."
echo ""
echo "  If you see 'pairing required', run:"
echo "    docker compose --profile cli run --rm openclaw-cli devices list"
echo "    docker compose --profile cli run --rm openclaw-cli devices approve <ID>"
echo ""
echo "  Useful commands:"
echo "    docker compose logs -f openclaw-gateway"
echo "    docker compose ps"
echo "    docker compose restart openclaw-gateway"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
